# Generated by Django 3.2.8 on 2021-10-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service3_shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('service3_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service3_shared.service3type')),
            ],
        ),
    ]
