# Generated by Django 3.2.8 on 2021-10-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service3_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service3',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='service3',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
