# Generated by Django 3.2.8 on 2021-10-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=202),
        ),
    ]
