# Generated by Django 3.2.8 on 2021-10-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service3', '0002_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
    ]
